use_frameworks!

platform :ios, '8.0'

target 'WYNetworking_Example' do
  pod 'WYNetworking', :path => '../'

  target 'WYNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
